Tạo mảng với các phần tự được lặp lại từ một mảng khác. Cho mảng sau:

`arr = np.array([1,2,3])`

a) Tạo mảng mới, lặp lại mỗi phần tử của arr 2 lần

b) Tạo mảng mới, lặp lại mảng arr 2 lần

In [1]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [2]:
# Lặp lại mỗi phần tử của arr 2 lần
x = np.repeat(arr, 2)
print(x)

[1 1 2 2 3 3]


In [3]:
# Lặp lại mảng arr 2 lần
y = np.tile(arr, 2)
print(y)

[1 2 3 1 2 3]
