In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('heart.csv')
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [3]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [4]:
categorical_cols = data.select_dtypes(include = ['object_'])
categorical_cols_names = categorical_cols.keys()
num_cols = X.select_dtypes(include = ['integer'])
num_cols_names = num_cols.keys()
print(num_cols_names)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR'], dtype='object')


In [5]:
print(categorical_cols)
print(list(categorical_cols))

    Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0     M           ATA     Normal              N       Up
1     F           NAP     Normal              N     Flat
2     M           ATA         ST              N       Up
3     F           ASY     Normal              Y     Flat
4     M           NAP     Normal              N       Up
..   ..           ...        ...            ...      ...
913   M            TA     Normal              N     Flat
914   M           ASY     Normal              N     Flat
915   M           ASY     Normal              Y     Flat
916   F           ATA        LVH              N     Flat
917   M           NAP     Normal              N       Up

[918 rows x 5 columns]
['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']


In [6]:

# print(y)

In [7]:
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder

# Label Encoding

In [8]:
# tobe_label_encoded = list({'Sex':X.iloc[:,0],'ExerciseAngina':X.iloc[:,-1]})
# tobe_labelencoded = list(i for i in categorical_cols_names if categorical_cols[i].nunique() == 2)
# print(tobe_labelencoded)


tobe_label_encoded = categorical_cols[['Sex','ExerciseAngina']]
# print(tobe_label_encoded)
le = LabelEncoder()
tobe_label_encoded.iloc[:,0] = le.fit_transform(tobe_label_encoded.iloc[:,0])
tobe_label_encoded.iloc[:,1] = le.fit_transform(tobe_label_encoded.iloc[:,1])
print(tobe_label_encoded)

     Sex  ExerciseAngina
0      1               0
1      0               0
2      1               0
3      0               1
4      1               0
..   ...             ...
913    1               0
914    1               0
915    1               1
916    0               0
917    1               0

[918 rows x 2 columns]


c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\pandas\core\indexing.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value
c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


# One hot encoding

In [9]:
# ohe = OneHotEncoder(sparse=False)
# tobe_oh_encoded = pd.DataFrame({'ChestPainType':X.iloc[:,2],'RestingECG':X.iloc[:,6],'ST_Slope' : X.iloc[:,10]})
# tobe_oh_encoded = ohe.fit_transform(tobe_oh_encoded)
# tobe_oh_encoded = pd.DataFrame(tobe_oh_encoded)
# # tobe_oh_encoded.columns = []
# print(tobe_oh_encoded)

In [10]:
ohe = OneHotEncoder(sparse=False)
tobe_oh_encoded = pd.DataFrame({'ChestPainType':X.iloc[:,2],'RestingECG':X.iloc[:,6],'ST_Slope' : X.iloc[:,10]})
# tobe_oh_encoded = ohe.fit_transform(tobe_oh_encoded)
oh_encoded = pd.get_dummies(tobe_oh_encoded,prefix='dummy')
# tobe_oh_encoded.columns = []
print(oh_encoded)

     dummy_ASY  dummy_ATA  dummy_NAP  dummy_TA  dummy_LVH  dummy_Normal  \
0            0          1          0         0          0             1   
1            0          0          1         0          0             1   
2            0          1          0         0          0             0   
3            1          0          0         0          0             1   
4            0          0          1         0          0             1   
..         ...        ...        ...       ...        ...           ...   
913          0          0          0         1          0             1   
914          1          0          0         0          0             1   
915          1          0          0         0          0             1   
916          0          1          0         0          1             0   
917          0          0          1         0          0             1   

     dummy_ST  dummy_Down  dummy_Flat  dummy_Up  
0           0           0           0         1  

# Standard Scaling

In [11]:
scaler = StandardScaler()
num_cols_scaled = pd.DataFrame(scaler.fit_transform(num_cols),columns=num_cols_names)
print(num_cols_scaled)

          Age  RestingBP  Cholesterol  FastingBS     MaxHR
0   -1.433140   0.410909     0.825070  -0.551341  1.382928
1   -0.478484   1.491752    -0.171961  -0.551341  0.754157
2   -1.751359  -0.129513     0.770188  -0.551341 -1.525138
3   -0.584556   0.302825     0.139040  -0.551341 -1.132156
4    0.051881   0.951331    -0.034755  -0.551341 -0.581981
..        ...        ...          ...        ...       ...
913 -0.902775  -1.210356     0.596393  -0.551341 -0.188999
914  1.536902   0.627078    -0.053049   1.813758  0.164684
915  0.370100  -0.129513    -0.620168  -0.551341 -0.857069
916  0.370100  -0.129513     0.340275  -0.551341  1.461525
917 -1.645286   0.302825    -0.217696  -0.551341  1.422226

[918 rows x 5 columns]


In [12]:
data_prepared = pd.concat([tobe_label_encoded,oh_encoded,num_cols_scaled],axis = 1)

In [13]:
print(data_prepared)

     Sex  ExerciseAngina  dummy_ASY  dummy_ATA  dummy_NAP  dummy_TA  \
0      1               0          0          1          0         0   
1      0               0          0          0          1         0   
2      1               0          0          1          0         0   
3      0               1          1          0          0         0   
4      1               0          0          0          1         0   
..   ...             ...        ...        ...        ...       ...   
913    1               0          0          0          0         1   
914    1               0          1          0          0         0   
915    1               1          1          0          0         0   
916    0               0          0          1          0         0   
917    1               0          0          0          1         0   

     dummy_LVH  dummy_Normal  dummy_ST  dummy_Down  dummy_Flat  dummy_Up  \
0            0             1         0           0           0         

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data_prepared,y,test_size=0.2,random_state = 0)

In [15]:
print(X_train.shape)
print(X_test.shape)

(734, 17)
(184, 17)


In [16]:
print(y_train.shape)
print(y_test.shape)

(734,)
(184,)


# Model 1 

In [17]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier()
clf1.fit(X_train,y_train)
y_pred1 = clf1.predict(X_test)
df = pd.DataFrame({"y":y_test,'y_pred':y_pred1})
df

y  y_pred
306  1       1
711  0       1
298  1       1
466  1       1
253  0       0
..  ..     ...
909  1       1
293  1       1
761  1       0
2    0       0
409  1       1

[184 rows x 2 columns]

In [18]:
from sklearn.metrics import r2_score,confusion_matrix,accuracy_score
print(r2_score(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))

0.41934700813205494
0.8586956521739131
[[61 16]
 [10 97]]


# Model 2

In [19]:
from sklearn.linear_model import LogisticRegression
clf2 = LogisticRegression()
clf2.fit(X_train,y_train)
y_pred2 = clf2.predict(X_test)
df = pd.DataFrame({"y":y_test,'y_pred':y_pred2})
df

y  y_pred
306  1       1
711  0       1
298  1       1
466  1       1
253  0       0
..  ..     ...
909  1       1
293  1       1
761  1       0
2    0       0
409  1       1

[184 rows x 2 columns]

In [20]:
from sklearn.metrics import r2_score,confusion_matrix,accuracy_score
print(r2_score(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))

0.2406845490957641
0.8152173913043478
[[56 21]
 [13 94]]


# Naive Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB
clf3 = GaussianNB()
clf3.fit(X_train,y_train)
y_pred3 = clf3.predict(X_test)
df = pd.DataFrame({"y":y_test,'y_pred':y_pred3})
df

y  y_pred
306  1       1
711  0       1
298  1       1
466  1       1
253  0       0
..  ..     ...
909  1       1
293  1       1
761  1       0
2    0       0
409  1       1

[184 rows x 2 columns]

In [22]:
from sklearn.metrics import r2_score,confusion_matrix,accuracy_score
print(r2_score(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))

0.26301735647530045
0.8206521739130435
[[56 21]
 [12 95]]
