In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('heart.csv')
print(data.shape)
data.head()

(918, 12)


Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [3]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [5]:
categorical_cols = data.select_dtypes(include = ['object_'])
categorical_cols_names = categorical_cols.keys()

num_cols = data.select_dtypes(include = ['integer'])
num_cols_names = num_cols.keys()



In [6]:
print(categorical_cols)

    Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0     M           ATA     Normal              N       Up
1     F           NAP     Normal              N     Flat
2     M           ATA         ST              N       Up
3     F           ASY     Normal              Y     Flat
4     M           NAP     Normal              N       Up
..   ..           ...        ...            ...      ...
913   M            TA     Normal              N     Flat
914   M           ASY     Normal              N     Flat
915   M           ASY     Normal              Y     Flat
916   F           ATA        LVH              N     Flat
917   M           NAP     Normal              N       Up

[918 rows x 5 columns]


In [7]:
print(categorical_cols_names)

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='object')


In [8]:
print(num_cols)

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  HeartDisease
0     40        140          289          0    172             0
1     49        160          180          0    156             1
2     37        130          283          0     98             0
3     48        138          214          0    108             1
4     54        150          195          0    122             0
..   ...        ...          ...        ...    ...           ...
913   45        110          264          0    132             1
914   68        144          193          1    141             1
915   57        130          131          0    115             1
916   57        130          236          0    174             1
917   38        138          175          0    173             0

[918 rows x 6 columns]


In [9]:
print(num_cols_names)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR',
       'HeartDisease'],
      dtype='object')


In [10]:
print(categorical_cols.describe())

        Sex ChestPainType RestingECG ExerciseAngina ST_Slope
count   918           918        918            918      918
unique    2             4          3              2        3
top       M           ASY     Normal              N     Flat
freq    725           496        552            547      460


In [11]:
tobe_labelencoded = list(i for i in categorical_cols_names if categorical_cols[i].nunique() == 2)
print(X[tobe_labelencoded])

    Sex ExerciseAngina
0     M              N
1     F              N
2     M              N
3     F              Y
4     M              N
..   ..            ...
913   M              N
914   M              N
915   M              Y
916   F              N
917   M              N

[918 rows x 2 columns]


In [12]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[num_cols_names[:-1]] = scaler.fit_transform(X[num_cols_names[:-1]])
X

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   -1.433140   M           ATA   0.410909     0.825070  -0.551341     Normal   
1   -0.478484   F           NAP   1.491752    -0.171961  -0.551341     Normal   
2   -1.751359   M           ATA  -0.129513     0.770188  -0.551341         ST   
3   -0.584556   F           ASY   0.302825     0.139040  -0.551341     Normal   
4    0.051881   M           NAP   0.951331    -0.034755  -0.551341     Normal   
..        ...  ..           ...        ...          ...        ...        ...   
913 -0.902775   M            TA  -1.210356     0.596393  -0.551341     Normal   
914  1.536902   M           ASY   0.627078    -0.053049   1.813758     Normal   
915  0.370100   M           ASY  -0.129513    -0.620168  -0.551341     Normal   
916  0.370100   F           ATA  -0.129513     0.340275  -0.551341        LVH   
917 -1.645286   M           NAP   0.302825    -0.217696  -0.551341     Normal   

        MaxHR ExerciseAngina  Oldpeak ST_Slope  
0    1.382928              N      0.0       Up  
1    0.754157              N      1.0     Flat  
2   -1.525138              N      0.0       Up  
3   -1.132156              Y      1.5     Flat  
4   -0.581981              N      0.0       Up  
..        ...            ...      ...      ...  
913 -0.188999              N      1.2     Flat  
914  0.164684              N      3.4     Flat  
915 -0.857069              Y      1.2     Flat  
916  1.461525              N      0.0     Flat  
917  1.422226              N      0.0       Up  

[918 rows x 11 columns]

In [14]:
le = LabelEncoder()
# X['Sex'] = le.fit_transform(X['Sex'])
# X['ExerciseAngina'] = le.fit_transform(X['ExerciseAngina'])
X[tobe_labelencoded] = le.fit_transform(tobe_labelencoded)

In [62]:
print(X.iloc[:,1].nuique())

AttributeError: 'Series' object has no attribute 'nuique'

In [41]:
tobe_oh_encoded = pd.DataFrame({'ChestPainType':X.iloc[:,2],'RestingECG':X.iloc[:,6],'ST_Slope' : X.iloc[:,10]})

In [42]:
print(tobe_oh_encoded)

    ChestPainType RestingECG ST_Slope
0             ATA     Normal       Up
1             NAP     Normal     Flat
2             ATA         ST       Up
3             ASY     Normal     Flat
4             NAP     Normal       Up
..            ...        ...      ...
913            TA     Normal     Flat
914           ASY     Normal     Flat
915           ASY     Normal     Flat
916           ATA        LVH     Flat
917           NAP     Normal       Up

[918 rows x 3 columns]


In [19]:
print(X)

          Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS  \
0   -1.433140    1           ATA   0.410909     0.825070  -0.551341   
1   -0.478484    1           NAP   1.491752    -0.171961  -0.551341   
2   -1.751359    1           ATA  -0.129513     0.770188  -0.551341   
3   -0.584556    1           ASY   0.302825     0.139040  -0.551341   
4    0.051881    1           NAP   0.951331    -0.034755  -0.551341   
..        ...  ...           ...        ...          ...        ...   
913 -0.902775    1            TA  -1.210356     0.596393  -0.551341   
914  1.536902    1           ASY   0.627078    -0.053049   1.813758   
915  0.370100    1           ASY  -0.129513    -0.620168  -0.551341   
916  0.370100    1           ATA  -0.129513     0.340275  -0.551341   
917 -1.645286    1           NAP   0.302825    -0.217696  -0.551341   

    RestingECG     MaxHR  ExerciseAngina  Oldpeak ST_Slope  
0       Normal  1.382928               0      0.0       Up  
1       Normal  0.754157 

In [43]:
tobe_oh_encoded = ohe.fit_transform(tobe_oh_encoded)

AttributeError: 'numpy.ndarray' object has no attribute 'keys'

In [44]:
print(tobe_oh_encoded)

[[0. 1. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]]


In [54]:
X = pd.DataFrame(X)

In [55]:
X = X.drop(['ChestPainType','RestingECG','ST_Slope'],axis = 1)

In [56]:
print(X)

          Age  Sex  RestingBP  Cholesterol  FastingBS     MaxHR  \
0   -1.433140    1   0.410909     0.825070  -0.551341  1.382928   
1   -0.478484    1   1.491752    -0.171961  -0.551341  0.754157   
2   -1.751359    1  -0.129513     0.770188  -0.551341 -1.525138   
3   -0.584556    1   0.302825     0.139040  -0.551341 -1.132156   
4    0.051881    1   0.951331    -0.034755  -0.551341 -0.581981   
..        ...  ...        ...          ...        ...       ...   
913 -0.902775    1  -1.210356     0.596393  -0.551341 -0.188999   
914  1.536902    1   0.627078    -0.053049   1.813758  0.164684   
915  0.370100    1  -0.129513    -0.620168  -0.551341 -0.857069   
916  0.370100    1  -0.129513     0.340275  -0.551341  1.461525   
917 -1.645286    1   0.302825    -0.217696  -0.551341  1.422226   

     ExerciseAngina  Oldpeak  
0                 0      0.0  
1                 0      1.0  
2                 0      0.0  
3                 0      1.5  
4                 0      0.0  
..       

In [47]:
# data_prepared = np.concatenate([X,tobe_oh_encoded],axis = 1)

In [49]:
# print(data_prepared.shape)

(918, 21)


In [53]:
# data_prepared = pd.DataFrame(data_prepared)
# # data_prepared = data_prepared.drop(['ChestPainType','RestingECG','ST_Slope'],axis = 1)
# print(data_prepared)

In [57]:
tobe_oh_encoded = pd.DataFrame(tobe_oh_encoded)
data_prepared = pd.concat([X,tobe_oh_encoded],axis = 1)

In [58]:
print(data_prepared)

          Age  Sex  RestingBP  Cholesterol  FastingBS     MaxHR  \
0   -1.433140    1   0.410909     0.825070  -0.551341  1.382928   
1   -0.478484    1   1.491752    -0.171961  -0.551341  0.754157   
2   -1.751359    1  -0.129513     0.770188  -0.551341 -1.525138   
3   -0.584556    1   0.302825     0.139040  -0.551341 -1.132156   
4    0.051881    1   0.951331    -0.034755  -0.551341 -0.581981   
..        ...  ...        ...          ...        ...       ...   
913 -0.902775    1  -1.210356     0.596393  -0.551341 -0.188999   
914  1.536902    1   0.627078    -0.053049   1.813758  0.164684   
915  0.370100    1  -0.129513    -0.620168  -0.551341 -0.857069   
916  0.370100    1  -0.129513     0.340275  -0.551341  1.461525   
917 -1.645286    1   0.302825    -0.217696  -0.551341  1.422226   

     ExerciseAngina  Oldpeak    0    1    2    3    4    5    6    7    8    9  
0                 0      0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  
1                 0      1.0  0.0